liteflow:
  print-banner: false # 关闭启动时 LiteFlow 的 ASCII banner
  parse-mode: PARSE_ONE_ON_FIRST_EXEC # 首次执行时解析规则一次，后续不再解析
  rule-source-ext-data-map:
    #    url: jdbc:mysql://localhost:3306/poseidon
    #    driverClassName: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: 123456
    applicationName: jeecg # 当前应用名称，决定加载数据库中哪条 chain
    #是否开启SQL日志
    sqlLogEnabled: true # 启用 SQL 打印
    #是否开启SQL数据轮询自动刷新机制 默认不开启
    #    pollingEnabled: false
    #SQL数据轮询时间间隔(s) 默认为60s
    #    pollingIntervalSeconds: 60
    #规则配置后首次轮询的起始时间(s) 默认为60s
    #    pollingStartSeconds: 60
    #以下是chain表的配置，这个一定得有
    #编排规则表的表名
    chainTableName: airag_flow  # 规则表名
    #编排规则表中应用名称存储字段名
    chainApplicationNameField: application_name  # 表中 app 字段
    #规则名称存储的字段名  # 规则链名称字段
    chainNameField: id
    #EL表达式的字段(只存EL)  # 存放 EL 表达式的字段
    elDataField: chain
    #以下是决策路由字段的配置，如果你没用到决策路由，可以不配置
    #    routeField: route
    #    namespaceField: namespace
    #    #是否启用这条规则
    #    chainEnableField: enable
    #    #规则表自定义过滤SQL
    chainCustomSql: select id, application_name, chain from airag_flow where status = 'enable' and chain is not null
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
#    scriptTableName: script
#    scriptApplicationNameField: application_name
#    scriptIdField: script_id
#    scriptNameField: script_name
#    scriptDataField: script_data
#    scriptTypeField: script_type
#    scriptLanguageField: script_language
#    #是否启用这条脚本
#    scriptEnableField: enable
#    #脚本表自定义过滤SQL
#    scriptCustomSql: 这里设置自定义脚本表SQL
