liteflow:
  print-banner: false
  parse-mode: PARSE_ONE_ON_FIRST_EXEC
  #指定从数据库加载流程
  rule-source-ext-data-map:
    #    url: jdbc:mysql://localhost:3306/poseidon
    #    driverClassName: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: 123456
    applicationName: jeecg
    #是否开启SQL日志
    sqlLogEnabled: true
    #是否开启SQL数据轮询自动刷新机制 默认不开启
    #    pollingEnabled: false
    #SQL数据轮询时间间隔(s) 默认为60s
    #    pollingIntervalSeconds: 60
    #规则配置后首次轮询的起始时间(s) 默认为60s
    #    pollingStartSeconds: 60
    #以下是chain表的配置，这个一定得有
    #编排规则表的表名
    chainTableName: airag_flow
    #编排规则表中应用名称存储字段名 应用名称
    chainApplicationNameField: application_name
    #规则名称存储的字段名
    chainNameField: id
    #EL表达式的字段(只存EL) 流程定义（EL 表达式，如 THEN(start, llm, end)）
    elDataField: chain
    #以下是决策路由字段的配置，如果你没用到决策路由，可以不配置
    #    routeField: route
    #    namespaceField: namespace
    #    #是否启用这条规则
    #    chainEnableField: enable
    #    #规则表自定义过滤SQL
    chainCustomSql: select id, application_name, chain from airag_flow where status = 'enable' and chain is not null
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
#    scriptTableName: script
#    scriptApplicationNameField: application_name
#    scriptIdField: script_id
#    scriptNameField: script_name
#    scriptDataField: script_data
#    scriptTypeField: script_type
#    scriptLanguageField: script_language
#    #是否启用这条脚本
#    scriptEnableField: enable
#    #脚本表自定义过滤SQL
#    scriptCustomSql: 这里设置自定义脚本表SQL





#server:
#  port: 7008
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  autoconfigure:
#    exclude:
#      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
#  datasource:
#    druid:
#      stat-view-servlet:
#        enabled: true
#        loginUsername: admin
#        loginPassword: 123456
#        allow:
#      web-stat-filter:
#        enabled: true
#    dynamic:
#      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
#        # 连接池的配置信息
#        # 初始化大小，最小，最大
#        initial-size: 5
#        min-idle: 5
#        maxActive: 1000
#        # 配置获取连接等待超时的时间
#        maxWait: 60000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        timeBetweenEvictionRunsMillis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        minEvictableIdleTimeMillis: 300000
#        #        validationQuery: SELECT 1
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        # 打开PSCache，并且指定每个连接上PSCache的大小
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        # !!!!!mysql
#        #        filters: stat,slf4j,wall
#        # !!!!!DM
#        filters: stat,slf4j
#        # 允许SELECT语句的WHERE子句是一个永真条件
#        #        wall:
#        #          selectWhereAlwayTrueCheck: false
#        # 打开mergeSql功能；慢SQL记录
#        stat:
#          merge-sql: true
#          slow-sql-millis: 5000
#      datasource:
#        master:
#          ## !!!!!MYSQL
#          url: jdbc:mysql://192.168.1.221:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#          username: sxwl
#          password: sxwl@221
#          driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#jeecg:
#  ai-rag:
#    embed-store:
#      host: "localhost"
#      port: 15432
#      database: "postgres"
#      user: "postgres"
#      password: "123456"
#      table: "embeddings"
#
#
#
